
[flipping]

	[flipping.advanced]
		item_blacklist = ""
		manipulation_check = true

	[flipping.basic]
		minimum_profit_percentage = 0.25384617
		minimum_profit = 500000
		alert_sounds = true
		enabled_only_in_skyblock = true
		minimum_demand = 10
		enabled = true

[money_saving]
	best_selling_method = true
	best_selling_method_item_overlay = false

[confidential]
	debug = false
	api_key = "c52f5e32-39d9-4677-9ce6-67e0bdcd30a3"

[qol]
	hide_spam_messages = true

