
[container]

	[container.container]
		container_preview = false
		searchbar = false
		auction_highlight = false
		slot_binding = true
		container_preview_ = 0
		container_buttons_ = 0
		wardrobe_hotkey = true

	[container.items]
		attribute_abbreviation = false
		armor_display = false
		item_time_display = true
		max_supercraft = true
		jyrre_time_display = true
		equipment_display = false

[combat]

	[combat.slayer]
		announce_boss_chat = 0
		boss_highlight = false
		miniboss_highlight = false
		slayer_spawn_warning = 0
		announce_miniboss_chat = 0

	[combat.gyrokinetic_wand]
		cells_alignment_timer = false
		cells_alignment_alert = false

	[combat.combat]
		mana_drain_range = false
		combo_display = false
		broken_hyperion = false
		low_health_alert = 0.0
		damage_tracker = false
		damage_tracer = 0
		ragnarok_detection = true

	[combat.bestiary]
		broodmother_detect = false
		bestiary_counters = 0
		kill_counter = false
		hitbox_color = "255,0,0,0"
		bestiary_gui = true

	[combat.dungeon]
		watcher_alert = false
		dungeon_rejoin = 0

[economy]

	[economy.coins]
		coin_tracker = 0

	[economy.economy]
		item_price = false
		bits_alert = 0
		economy_refresh = 60
		coin_tracker = 0

	[economy.pricing]
		trade_value = false
		container_value = 0
		item_price = 0
		price_type = 0
		single_attribute = true

[mining]

	[mining.jinx]
		powder_chest_detect = 0
		powder_chest_hider = 0
		powder_tracker = 0
		2x_powder_alert = true

	[mining.crystal_hollows]
		wishing_compass_locator = false

	[mining.powder]
		powder_tracker = 0

	[mining.mining]
		wishing_compass_locator = false
		pick_display = false

	[mining.shaft]
		shaft_transfer = false
		corpse_announce = false
		corpse_waypoints = true
		commission_waypoints = 0
		commission_announce = false
		commissions_display = false
		fossil_helper = true

[dungeon]

	[dungeon.star_detect]
		star_mob_highlight = 0
		star_highlight_color = "255,0,255,0"

	[dungeon.chests]
		dungeon_profit = false
		croesus_highlight = false

[rift]

	[rift.rift]
		ddr_helper = true
		enigma_soul_waypoints = 0
		montezuma_soul_waypoints = false

	[rift.vampire]
		announce_mania_phase = 0
		vampire_attack_display = true
		effigy_waypoint = true
		vampire_hitbox = true
		enlarge_impel_message = false

	[rift.awooga_v2]
		weird_tuba_timer = false
		weird_tuba_alert = false

[general]

	[general.skills]
		skill_tracker = 0

	[general.general]
		custom_emotes = false
		armor_display = false
		render_waypoint = 0
		draw_waypoint = 0
		abiphone_blocker = false
		widget_display = true
		remove_selfie_mode = false
		equipment_display = false
		skyblock_xp_alert = true
		skill_tracker = 0
		recent_server_alert = 0
		text_shadow_toggle = true

	[general.server]
		fairy_soul_waypoints = 0
		hide_on_bush = ""
		server_status = true
		server_alert = true
		skyblock_stats_display = false
		hide_close_players = 0
		hide_all_particles = false
		hide_far_entities = 0

	[general.timer]
		reminder_text = ""
		reminder_time = 0
		item_cooldown_alert = false

	[general.webhook]
		discord_webhook = ""

	[general.inventory]
		searchbar = false
		jyrre_time_display = true
		slot_binding = false
		wardrobe_hotkey = false

	[general.yapping]
		custom_emotes = false
		autocorrect_command = false
		image_viewer = 0.0
		bridge_formatter = false
		autocomplete_commands = false
		autocorrect_commands = 0
		autocomplete_command = false

	[general.party_commands]
		"leave_command_(?leave)" = false
		"limbo_command_(?<limbo,_lobby,_l>)" = false
		"warp_command_(?warp)" = true
		party_chat_commands = 2
		leader_command_options = false
		"transfer_command_(?transfer)" = true
		leader_chat_commands = false
		"demote_command_(?demote)" = true
		"coords_command_(?coords)" = true
		"rps_command_(?rps)" = true
		party_command_options = false
		"invite_command_(?invite)" = true
		"stream_command_(?<streamopen,_stream>_[num])" = true
		"help_command_(?help)" = true
		"allinvite_command_(?<allinvite,_allinv>)" = true
		"8ball_command_(?8ball)" = true
		"dice_command_(?<dice,_roll>)" = true
		"women_command_(?<w,_waifu,_women>)" = true
		"slander_command_(?<racist,_gay,_cringe>)" = true
		"promote_command_(?promote)" = true
		"coinflip_command_(?<coin,_flip,_coinflip,_cf>)" = true

	[general.party]
		auto_transfer_back = false
		auto_join_reparty = false
		whitelist_rejoin = false

	[general.essential]
		api_key = ""
		volcaddons_toggle = true
		socket_toggle = true
		skyblock_toggle = true

[crimson_isles]

	[crimson_isles.fishing]
		golden_fish_timer = false
		announce_mythic_creature_spawn = 0
		detect_mythic_lava_creature = false
		trophy_fish_counter = 0
		trophy_fish_overlay = false
		mythic_lava_creature_detect = false

	[crimson_isles.vanquisher]
		vanquisher_detection_sound = false
		vanquisher_auto-warp = ""
		vanquisher_detection = true
		announce_vanquisher_chat = 0
		vanquisher_counter = 0

	[crimson_isles.vanquisher_alert]
		vanquisher_detection_sound = true
		vanquisher_auto-warp = ""
		vanquisher_detection = true
		announce_vanquisher_chat = 1

	[crimson_isles.vanquisher_counter]
		vanquisher_counter = 1

[hub]

	[hub.inquisitor]
		detect_inquisitor = false
		announce_inquisitor_chat = 0
		inquisitor_counter = 0

	[hub.diana]
		diana_warp = false
		diana_waypoint = false

	[hub.griffin_burrow]
		burrow_chat_alert = false
		burrow_amogus_alert = false
		burrow_detection = false

[kuudra]

	[kuudra.kuudra]
		kuudra_hp_display = false
		show_crate_waypoints = true
		show_supply_piles = false
		"show_supply/fuel_waypoints" = true
		kuudra_spawn = false
		"auto_'/kv'_pf" = false
		crate_edit = false
		kuudra_splits = true

	[kuudra.kuudra_profit]
		"kuudra_profit_tracker_(wip)" = 0
		kuudra_profit_tracker = 0
		kuudra_profit = true
		minimum_god_roll = 50
		tabasco_enjoyer = false

	[kuudra.kuudra_alert]
		mount_ballista_alert = true
		kuudra_alerts = true
		unready_alert = true
		stunner_alert = ""
		kuudra_alert_options = false
		stun_alert = true
		token_alert = 0
		cannonear_alert = ""
		fresh_tools_alert = true
		no_key_alert = true
		choose_route_alert = true
		fuel_percent_alert = true
		pickup_supply_alert = true
		stunner_eaten_alert = true
		building_alert = true
		dropship_alert = true

[farming]

	[farming.pests]
		desk_highlight = false
		pest_alert = false
		infested_alert = 0
		infestation_alert = false
		plot_highlight = false
		spray_display = false
		pesthunter_display = false

	[farming.garden_webhook]
		webhook_timer = 0
		discord_webhook = ""

	[farming.farming]
		jacob_reward_highlight = true

	[farming.garden]
		garden_tab_display = false
		garden_warp_override = false
		garden_box_plot = false
		composter_display = 0
		next_visitor_display = false
		jacob_reward_highlight = true
		garden_plot_box = false

[garden]

	[garden.garden]
		garden_tab_display = false
		garden_warp_override = false
		composter_alert = false
		next_visitor_display = false

[event]

	[event.chocolate_factory]
		egg_announce = 0
		egg_timers = false
		stray_alert = 0
		chocolate_overlay = false
		rabbit_highlight = 0
		egg_waypoints = false
		worker_highlight = false

	[event.inquisitor]
		detect_inquisitor = false
		announce_inquisitor_chat = 0
		inquisitor_counter = 0

	[event.mythological_ritual]
		diana_warp = false
		burrow_detection = 0
		diana_waypoint = false

	[event.skyblock]
		bingo_card_overlay = 0
		calendar_time = false

	[event.bingo]
		bingo_card_overlay = 0

	[event.great_spook]
		primal_fear_alert = false
		math_teacher_solver = false
		primal_fear_highlight = false

[party]

	[party.message]
		party_leader_only = false
		party_join_message = ""
		guild_join_message = ""

	[party.party_commands]
		party_chat_commands = true
		leader_chat_commands = true

	[party.party]
		anti_ghost_party = true
		party_join_message = ""
		auto_transfer = 0
		server_kick_announce = ""
		auto_join_reparty = true
		guild_join_message = ""
		whitelist_rejoin = true

