
[general]
	rend_arrows = false
	waypoint_color = "255,255,0,255"
	"➤_leader_commands" = false
	chat_type_waypoint_rendering = 0
	stops_entity_death_animation = false
	draw_chat_waypoints = 0
	confirm_leader_commands = false
	invited_player_name = ""
	detect_reaper_armor = false
	party_and_warp_on_chat_message = ""
	skyblock_xp_gain_message = false
	treecap_timer = false
	waypoint_beacon_height = 150
	party_commands = false
	steak-able_vamp_hitbox = false

[kuudra]
	stop_rendering_mob_nametags_in_kuudra = false
	shows_kuudra = false
	supply_pearl_lineup = true
	custom_supply_drop_message = false
	"not_stunning?" = false
	accurate_supply_waypoints = false
	highlight_teammates_in_kuudra = false
	teammate_color = "255,255,0,255"
	"no_pre!_no_second!" = false
	supply_drop_waypoints = false
	draw_hitboxes_around_freshers = false
	breaking_piles = false
	build_helper = false
	stop_rendering_useless_perks = false
	notify_party_on_fresh = false

[hud]
	draw_with_shadow = false

	[hud.widget]
		custom_widget_text = ""
		frozen_corpse_widget = false
		trophy_fish_widget = false
		pet_widget = false
		stats_widget = false
		widget_display = false
		pest_widget = false
		commission_widget = false
		crop_milestone_widget = false
		custom_widget = false
		visitor_widget = false
		jacob_widget = false
		bestiary_widget = false
		powder_widget = false

	[hud.poison]
		poison_display = false

	[hud.clock]
		clock_display = false

	[hud.align]
		align_display = false
		highlight_players_in_align_radius = false

	[hud.legion]
		legion_display = false

	[hud.mana]
		mana_enchant_calc = false
		endstone_sword_party_notify = false
		cumulative_fero_mana = 0
		endstone_sword_mana_drain_range = false
		cumulative_strong_mana = 0

	[hud.blaze]
		blaze_display = false

	[hud.fatal_tempo]
		"➤_fatal_tempo_show_time_left" = true
		"➤_fatal_tempo_show_title" = true
		fatal_tempo_settings = 0
		"➤_fatal_tempo_settings" = 0
		fatal_tempo_timer_scale = 1.0
		"➤_fatal_tempo_show_percent" = true
		fatal_tempo_display = false

	[hud.bestiary]
		mob_highlight_counter = false

	[hud.visitor]
		next_visitor_display = 0

	[hud.miniboss]
		miniboss_display = false

	[hud.champion]
		champion_display = false

	[hud.gyro]
		gyro_display = false
		mage_gyro = false

[bestiary]
	mob_esp = ""
	armor_stand_esp_color = "255,0,255,0"
	player_esp_color = "255,255,0,255"
	mob_esp_color = "255,255,255,0"
	armor_stand_highlight_color = "255,0,255,0"
	matcho = false
	"matcho!" = false
	arachnes_keeper = false
	player_names_esp = ""
	player_highlight_color = "255,255,0,255"
	armor_stand_names_esp = ""
	mob_highlight = ""
	armor_stand_names_highlight = ""
	player_highlight = ""
	mob_highlight_color = "255,255,255,0"

[crimson_isle]
	announce_vanquishers = false
	trophy_fish_session_counter = false
	announce_jawbus = false
	announce_plhlegblasts = false
	announce_thunder = false
	better_magma_boss_message = false

[mining]
	mineshaft_pity = false
	mineshaft_waypoints = false

[utilities]
	dev_commands = false
	damage_tracker = false

["beta_(wip)"]
	lapis_only = false
	gyro_range = false
	agro_range = false
	tracks_damage_armor_stands = false
	totem_color_opacity = 0.25
	agro_range_color = "255,255,0,0"
	totem_range = false
	gyro_color_opacity = 0.5
	agro_color_opacity = 0.5
	removed_boss_dialouge = false
	totem_range_options = 0
	gyro_range_color = "255,255,0,255"
	totem_range_color = "255,0,255,255"
	mineshaft_helper = false

[qol]
	toggle_block_highlight = false
	remove_npc_dialouge_on_garden = false
	remove_boss_dialouge = false
	remove_discord_warnings = false
	highlight_color = "255,0,255,0"

